### PR TITLE
Refactor -- General cleanup/Async/Error Messaging

### PR DESCRIPTION
**Pull request by robertlopezdev**
Hello,

During a recent discussion this repo was mentioned, so I explored refactoring. The key changes include:

- Transitioning to asynchronous I/O using `tokio` for more efficient processing of large directories of React component files.
- Enhancing error messaging to be more descriptive, utilizing the `anyhow` crate for better error handling.
- Cleaning up the syntax for improved readability and maintainability.

I have ensured that all unit tests pass and that the output from the `test/components` is consistent with the original version's output. 

This refactor introduces dependencies on `anyhow` and `async_recursion` to facilitate the transition to async. If these additions are a concern, I am open to discussing alternatives or reverting to the initial synchronous rewrite I committed, which still offers improved error messaging, syntax and some cleaning up of un-needed cloning.

Open to any discussions or requests for changes. Looking forward to your thoughts!

Best regards,

Robert Lopez

### CODE REVIEW

**Review by mpeterdev — CHANGES_REQUESTED** [review]
awesome! I have been hoping for an improvement sweep like this to take place

One regression that was not accounted for in unit tests: in config files, the property expected is now `account_id` instead of `account`

You can reproduce by running with `cargo run -- -c` in the `test` dir

**Comment by robertlopezdev** [comment]
> awesome! I have been hoping for an improvement sweep like this to take place
> 
> One regression that was not accounted for in unit tests: in config files, the property expected is now `account_id` instead of `account`
> 
> You can reproduce by running with `cargo run -- -c` in the `test` dir

Did not catch that, thanks. 

I made a commit to update this and to update the README to reflect the change as well.

**Comment by mpeterdev** [comment]
> > awesome! I have been hoping for an improvement sweep like this to take place
> > One regression that was not accounted for in unit tests: in config files, the property expected is now `account_id` instead of `account`
> > You can reproduce by running with `cargo run -- -c` in the `test` dir
> 
> Did not catch that, thanks.
> 
> I made a commit to update this and to update the README to reflect the change as well.

Sorry for not making this clearer: since this is a tool that is already widely used, we should resolve the regression and continue looking for `account` in the config file instead of changing to `account_id` there. Otherwise we are shipping a breaking change to users without good reason

**Comment by robertlopezdev** [comment]
> > > awesome! I have been hoping for an improvement sweep like this to take place
> > > One regression that was not accounted for in unit tests: in config files, the property expected is now `account_id` instead of `account`
> > > You can reproduce by running with `cargo run -- -c` in the `test` dir
> > 
> > 
> > Did not catch that, thanks.
> > I made a commit to update this and to update the README to reflect the change as well.
> 
> Sorry for not making this clearer: since this is a tool that is already widely used, we should resolve the regression and continue looking for `account` in the config file instead of changing to `account_id` there. Otherwise we are shipping a breaking change to users without good reason

Gotcha, reverted back to `account`.

**Review by mpeterdev — APPROVED** [review]

**Comment by mpeterdev** [comment]
thanks for you contribution @robertlopezdev !

**Pull request merged**
